Repository tipcat-net/tipcat-net-api, pull requests merged in 2021-10, with the labels that each got.

#42 Permission checker updated
  TipCatDotNet.Api/Filters/Authorization/HospitalityFacilityPermissions/MemberPermissionsAuthorizationHandler.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IPermissionChecker.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/PermissionChecker.cs
  TipCatDotNet.ApiTests/PermissionCheckerTests.cs
Labels: enhancement

#41 Issue - #34. Create features for payment by QR code.
  .gitignore
  TipCatDotNet.Api/Controllers/MemberController.cs
  TipCatDotNet.Api/Controllers/PaymentController.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/PaymentDetailsResponse.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/PaymentRequest.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/PaymentResponse.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IPaymentService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/MemberServiceExtensions.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/PaymentService.cs
  TipCatDotNet.Api/TipCatDotNet.Api.csproj
  TipCatDotNet.Api/TipCatDotNet.Api.xml
  TipCatDotNet.ApiTests/PaymentServiceTests.cs
Labels: enhancement

#43 A missing dependency on Payment Service added
  TipCatDotNet.Api/Infrastructure/ServiceCollectionExtensions.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/PaymentService.cs
Labels: bug

#44 Amazon S3 client configured
  TipCatDotNet.Api/Infrastructure/QrCodeGenerator.cs
  TipCatDotNet.Api/Startup.cs
  TipCatDotNet.Api/TipCatDotNet.Api.csproj
Labels: enhancement

#50 SlimFacilityResponse's methods were finalized and added to get endponts
  TipCatDotNet.Api/Controllers/FacilityController.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/SlimFacilityResponse.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/FacilityService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IFacilityService.cs
  TipCatDotNet.Api/TipCatDotNet.Api.xml
  TipCatDotNet.ApiTests/FacilityServiceTests.cs
Labels: enhancement

#59 Technical/ef design time factory
  TipCatDotNet.Api/Data/DesignTimeAetherDbContext.cs
  TipCatDotNet.Api/Infrastructure/ConnectionStringBuilder.cs
  TipCatDotNet.Api/Infrastructure/Constants/Common.cs
  TipCatDotNet.Api/Infrastructure/ServiceCollectionExtensions.cs
  TipCatDotNet.Api/Program.cs
  TipCatDotNet.Api/Startup.cs
Labels: technical
