Repository tipcat-net/tipcat-net-api, pull requests merged in 2021-11, with the labels that each got.

#64 Duplicated methods for getting members and facilities removed
  TipCatDotNet.Api/Controllers/FacilityController.cs
  TipCatDotNet.Api/Controllers/MemberController.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/Validators/FacilityRequestValidator.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/AccountService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/FacilityService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IFacilityService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IMemberService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/MemberService.cs
  TipCatDotNet.Api/TipCatDotNet.Api.xml
  TipCatDotNet.ApiTests/FacilityServiceTests.cs
  TipCatDotNet.ApiTests/MemberServiceTests.cs
Labels: technical

#69 DateTimeKind bug fixed
  TipCatDotNet.Api/Data/AetherDbContext.cs
  TipCatDotNet.Api/Infrastructure/Converters/DateTimeKindConverter.cs
Labels: bug

#74 Invitation revocation added
  TipCatDotNet.Api/Models/HospitalityFacilities/MemberResponse.cs
  TipCatDotNet.Api/Services/Auth/IInvitationService.cs
  TipCatDotNet.Api/Services/Auth/InvitationService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/MemberService.cs
  TipCatDotNet.ApiTests/MemberServiceTests.cs
Labels: enhancement

#76 Member transferring moved to the facility service
  TipCatDotNet.Api/Controllers/FacilityController.cs
  TipCatDotNet.Api/Controllers/MemberController.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/Validators/FacilityRequestValidator.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/Validators/MemberTransferValidator.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/FacilityService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IFacilityService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/IMemberService.cs
  TipCatDotNet.Api/Services/HospitalityFacilities/MemberService.cs
  TipCatDotNet.Api/TipCatDotNet.Api.xml
  TipCatDotNet.ApiTests/FacilityServiceTests.cs
  TipCatDotNet.ApiTests/MemberServiceTests.cs
Labels: enhancement

#78 Transaction logic was added
  TipCatDotNet.Api/Controllers/AccountController.cs
  TipCatDotNet.Api/Controllers/TransactionController.cs
  TipCatDotNet.Api/Data/AetherDbContext.cs
  TipCatDotNet.Api/Data/Models/Payment/Transaction.cs
  TipCatDotNet.Api/Models/Payments/TransactionResponse.cs
  TipCatDotNet.Api/Services/Payments/ITransactionService.cs
  TipCatDotNet.Api/Services/Payments/PaymentService.cs
  TipCatDotNet.Api/Services/Payments/TransactionService.cs
  TipCatDotNet.Api/TipCatDotNet.Api.xml
  TipCatDotNet.ApiTests/PaymentServiceTests.cs
  TipCatDotNet.ApiTests/TransactionServiceTests.cs
Labels: enhancement

#82 ITransactionService added to DI
  TipCatDotNet.Api/Infrastructure/ServiceCollectionExtensions.cs
Labels: bug

#91 The position propert limited to 64 characters
  TipCatDotNet.Api/Data/Models/HospitalityFacility/Member.cs
  TipCatDotNet.Api/Models/HospitalityFacilities/Validators/MemberRequestValidator.cs
  TipCatDotNet.ApiTests/MemberServiceTests.cs
Labels: technical
